### ISSUE TITLE
Suggestion; Avoid duplicating features from Quark and Inspirations

### ISSUE THREAD

**Issue by jonqrandom** [trickypr/Tiny-Improvments#2]
several items on your todo list are already addressed by the popular mods [Quark](https://minecraft.curseforge.com/projects/quark) and [Inspirations](https://minecraft.curseforge.com/projects/inspirations). some are addressed directly, like despawning item flashing in Quark, enchanted books having coloured ribbons based on rarity in Inspirations. others have been addressed differently to sarc's suggestions, like the way Quark has pigs drop tallow, which can be made into dyeable candles - Inspirations also addresses a pig issue, making it possible to de-saddle pigs without killing them.  
  
Quark and Inspirations are probably the two most popular "vanilla-like" mods, so it's a fairly safe assumption that anyone looking to extend the vanilla features of the game will already have them.

you may also want to check out [Serene Seasons](https://minecraft.curseforge.com/projects/serene-seasons), which has a very complete and configurable implementation of seasons - again, you may not find it worth your time to try to duplicate that functionality.

this is just off the top of my head - if you want me to actually try to figure out which features in your todo list are unique to your mod, just say so - i'm pretty sure i recognise about half the features from other mods, but in several cases they're done in single-feature mods, and centralising them would probably be a massive help to many players and pack makers :)

**Comment by trickypr** [comment]
Thanks for this information. I had no idea that there were other mods out there that did what I wanted to do with this mod. I will look into them and reassess what I want this mod to do.
